# Book settings
title: Open Science 101
author: NASA TOPS/VERSO
logo: docs/Open-Science-101/images/open_science_101_logo.png

format: jb-book

options:
  numbered: false

html:
  home_page_in_navbar: true
  use_issues_button: false
  use_repository_button: false
